export const countrycodes = [
  { name: `Afghanistan`, code: 'AF' },
  { name: `Australia`, code: 'AU' },
  { name: `Belarus`, code: 'BY' },
  { name: `Belgium`, code: 'BE' },
  { name: `Côte d'Ivoire`, code: 'CI' },
  { name: `Cuba`, code: 'CU' },
  { name: `Curaçao`, code: 'CW' },
  { name: `Czech Republic`, code: 'CZ' },
  { name: `Congo, the Democratic Republic of the`, code: 'CD' },
  { name: `France`, code: 'FR' },
  { name: `Germany`, code: 'DE' },
  { name: `Greece`, code: 'GR' },
  { name: `Iran, Islamic Republic of`, code: 'IR' },
  { name: `Iraq`, code: 'IQ' },
  { name: `Italy`, code: 'IT' },
  { name: `Liberia`, code: 'LR' },
  { name: `Libya`, code: 'LY' },
  { name: `Lithuania`, code: 'LT' },
  { name: `Netherlands`, code: 'NL' },
  { name: `Portugal`, code: 'PT' },
  { name: `Serbia`, code: 'RS' },
  { name: `Slovakia`, code: 'SK' },
  { name: `South Sudan`, code: 'SS' },
  { name: `Spain`, code: 'ES' },
  { name: `Sudan`, code: 'SD' },
  { name: `Sweden`, code: 'SE' },
  { name: `Syrian Arab Republic`, code: 'SY' },
  { name: `United Kingdom`, code: 'GB' },
  { name: `United States of America`, code: 'US' },
  { name: `Zimbabwe`, code: 'ZW' }
];
